Support MiceWeb

diff --git a/scripts/Channels/save b/scripts/Channels/save
--- a/scripts/Channels/save
+++ b/scripts/Channels/save
@@ -22,3 +22,12 @@ fi
 "$CMDDIR/../write_html"
 
 "$CMDDIR/save_recent"
+
+type -P miceweb &>/dev/null && ISINST=1 || ISINST=0
+if [ $ISINST -eq 1 ]
+then
+    miceweb save urls "Source - Channels.txt" --grep=^http
+else
+    >&2 echo "Error: miceweb is not installed (seeing https://github.com/Robotizing/MiceWeb/)"
+fi
+
