Support MiceWeb

diff --git a/scripts/Audio/Channels/save b/scripts/Audio/Channels/save
--- a/scripts/Audio/Channels/save
+++ b/scripts/Audio/Channels/save
@@ -27,3 +27,11 @@ then
     done
 fi
 "$CMDDIR/../write_html"
+
+type -P miceweb &>/dev/null && ISINST=1 || ISINST=0
+if [ $ISINST -eq 1 ]
+then
+    miceweb save urls "$FN" --grep=^http
+else
+    >&2 echo "Error: miceweb is not installed (seeing https://github.com/Robotizing/MiceWeb/)"
+fi
